### ISSUE TITLE
Deleting a level with challenges in it bugs out GUI + NPE

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/Challenges#116]
### Description
If you remove a whole Level using GUI that contained challenges - you will bug out both:
- **Edit Challenges**
- **Remove Challenges** 

, button - being unable to any further opening by clicking them. 
 Challenges are not deleted from base, but also not displayed in /challenges.

#### Steps to reproduce the behavior:
1. Create a level
2. Add challenges to it
3. Remove the whole Level via GUI
4. Try using **Edit Challenges** and **Remove Challenges** button in GUI
5. Take a look at base
6. Every click gives NPE in console: 
```
[02:13:04 ERROR]: Could not pass event InventoryClickEvent to BentoBox v1.5.0-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot.jar:git-Spigot-e4d0c66-1057710]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-e4d0c66-1057710]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-e4d0c66-1057710]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-e4d0c66-1057710]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2144) ~[spigot.jar:git-Spigot-e4d0c66-1057710]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot.jar:git-Spigot-e4d0c66-1057710]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-e4d0c66-1057710]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-e4d0c66-1057710]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-e4d0c66-1057710]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-e4d0c66-1057710]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-e4d0c66-1057710]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-e4d0c66-1057710]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-e4d0c66-1057710]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at world.bentobox.challenges.panel.CommonGUI.generateChallengeDescription(CommonGUI.java:302) ~[?:?]
        at world.bentobox.challenges.panel.admin.ListChallengesGUI.createChallengeIcon(ListChallengesGUI.java:138) ~[?:?]
        at world.bentobox.challenges.panel.admin.ListChallengesGUI.build(ListChallengesGUI.java:110) ~[?:?]
        at world.bentobox.challenges.panel.admin.AdminGUI.lambda$createButton$6(AdminGUI.java:281) ~[?:?]
        at world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:48) ~[?:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_191]
        at world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:46) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-e4d0c66-1057710]
        ... 15 more
```

#### Server / BentoBox information:
```
[01:58:29] [main/INFO]: [CHAT] Running PAPER 1.13.2.
[01:58:29] [main/INFO]: [CHAT] BentoBox version: 1.5.0-SNAPSHOT
[01:58:29] [main/INFO]: [CHAT] Loaded Game Worlds:
[01:58:29] [main/INFO]: [CHAT] acidisland (acidisland)
[01:58:29] [main/INFO]: [CHAT] skyblock (skyblock)
[01:58:29] [main/INFO]: [CHAT] Loaded Addons:
[01:58:29] [main/INFO]: [CHAT] AcidIsland 1.5.0-SNAPSHOT
[01:58:29] [main/INFO]: [CHAT] BentoBox-InvSwitcher 0.0.3-SNAPSHOT
[01:58:29] [main/INFO]: [CHAT] Biomes 0.4.5
[01:58:29] [main/INFO]: [CHAT] BSkyBlock 1.5.0
[01:58:29] [main/INFO]: [CHAT] Challenges 0.7.0-SNAPSHOT-#169
[01:58:29] [main/INFO]: [CHAT] Level 1.4.0
[01:58:29] [main/INFO]: [CHAT] Limits 0.2.0-SNAPSHOT
[01:58:29] [main/INFO]: [CHAT] SerbCraftAddon 2.2
[01:58:29] [main/INFO]: [CHAT] WelcomeWarps 1.4.1
```

#### Expected behavior / Additional context
- unSort challenges to be **Free**
- Be able to click both buttons in GUI

**Comment by BONNe** [comment]
Fixed in build #170
The issue was that I forgot to remove a level from challenges object if an admin removes level :)
It should now work without NPE
