### ISSUE TITLE
Some bugs when i do /is challenges

### ISSUE THREAD

**Issue by Typheonn** [BentoBoxWorld/Challenges#137]
### Description
Sometimes, when i do /is challenges, i saw this message message "An internal error occured while attempting to perform this command"

#### Steps to reproduce the behavior:
Run the server.
Make command : /is challenges.

#### Server / BentoBox information:
Bentobox : 1.5.1
Server : 1.13.2
Challenges : 0.7.5
Biomes : 1.5.0.0
Level : 1.5.0
WelcomeWarps: 1.5.0

#### Logs
[09:47:52] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'is challenges' in world.bentobox.bskyblock.commands.IslandCommand(island)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[patched_1.13.2.jar:git-Paper-629]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-629]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-629]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-629]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.LinkageError: world/bentobox/challenges/Settings
	at world.bentobox.challenges.ChallengesManager.getDataUniqueID(ChallengesManager.java:622) ~[?:?]
	at world.bentobox.challenges.ChallengesManager.getDataUniqueID(ChallengesManager.java:609) ~[?:?]
	at world.bentobox.challenges.ChallengesManager.getAllChallengeLevelStatus(ChallengesManager.java:1168) ~[?:?]
	at world.bentobox.challenges.panel.user.ChallengesGUI.<init>(ChallengesGUI.java:51) ~[?:?]
	at world.bentobox.challenges.commands.ChallengesCommand.execute(ChallengesCommand.java:80) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:245) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-629]
	... 14 more

**Comment by BONNe** [comment]
Caused by: java.lang.LinkageError: world/bentobox/challenges/Settings
It looks like some kind of reload issue.

Or multiple challenges addon at the same time.

**Comment by Olonto** [comment]
Hi.

Thanks you for your answer, i had several challenges addons ^^'

Sorry for the trouble, you can close the issue I think ^^'

**Comment by Typheonn** [comment]
Hi.

Thanks you for your answer, i had several challenges addons ^^'

Sorry for the trouble, you can close the issue I think ^^'
