### ISSUE TITLE
error in console when try creating a new challenge

### ISSUE THREAD

**Issue by Jupiterbe** [BentoBoxWorld/Challenges#155]
### Description

can't create new challenges

#### Steps to reproduce the behavior:

ingame:
1 /bsbadmin challenges
2 Click "Add new challenge'

then comes the error in the console

#### Server / BentoBox information:

Bskyblock ver 1.6.0-snapsot
Running Paper 1.14.3
Bemtobox 1.6.0-Snapshot-b1267
Biomes 1.52.1
Challenges 0.8.0-snapshot-#280
Level 1.6.0
Limits 0.2.3
MagicCobblestoneGenerator 1.5.0.1
WelcomeWarps 1.5.2

#### Screenshots / Server log

[18:35:29 ERROR]: Could not pass event InventoryClickEvent to BentoBox v1.6.0-SNAPSHOT-b1267
java.lang.NullPointerException: null
        at net.wesjd.anvilgui.AnvilGUI$AnvilListener.onInventoryClick(AnvilGUI.java:78) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.3.jar:git-Paper-129]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-129]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-129]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.3.jar:git-Paper-129]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2341) ~[patched_1.14.3.jar:git-Paper-129]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.3.jar:git-Paper-129]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.3.jar:git-Paper-129]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-129]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-129]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-129]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-129]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-129]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-129]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-129]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.3.jar:git-Paper-129]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[patched_1.14.3.jar:git-Paper-129]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-129]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by BONNe** [comment]
Could you try with #281 version?

**Comment by Jupiterbe** [comment]
i have installed the #281 but get  the same error.

**Comment by BONNe** [comment]
Anvil Gui is removed.
This issue should be solved.
