### ISSUE TITLE
many Errors in the Server console

### ISSUE THREAD

**Issue by general2811** [BentoBoxWorld/Challenges#167]
```
[19:32:12 ERROR]: Could not pass event InventoryCloseEvent to BentoBox v1.7.0-SNAPSHOT-b1331
java.lang.NullPointerException: null
        at net.wesjd.anvilgui.AnvilGUI$AnvilListener.onInventoryClose(AnvilGUI.java:102) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1336) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1331) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.wesjd.anvilgui.version.Wrapper1_14_R1.create(Wrapper1_14_R1.java:33) ~[?:?]
        at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:42) ~[?:?]
        at world.bentobox.challenges.panel.admin.EditChallengeGUI.lambda$createButton$15(EditChallengeGUI.java:548) ~[?:?]
        at world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:55) ~[?:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_221]
        at world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:53) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor635.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2347) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[19:32:28 ERROR]: Could not pass event InventoryClickEvent to RegionProtection v2.0.1
java.lang.IllegalStateException: Title not set
        at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.Container.getTitle(Container.java:48) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at org.bukkit.craftbukkit.v1_14_R1.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:69) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at eu.mip.alandioda.region.spigot.main.onPlayerClick(main.java:289) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor137.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2347) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[19:32:28 ERROR]: Could not pass event InventoryClickEvent to Parkour v5.3
java.lang.IllegalStateException: Title not set
        at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.Container.getTitle(Container.java:48) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at org.bukkit.craftbukkit.v1_14_R1.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:69) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at me.A5H73Y.Parkour.Listeners.PlayerInventoryListener.onInventoryInteract(PlayerInventoryListener.java:23) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor189.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2347) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[Paper-1.14.3.jar:git-Paper-"a41d51f0"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]```

**Comment by BONNe** [comment]
AnvilGui removed.
Issue solved.
