### ISSUE TITLE
Challenges Console Error, plugin don't open!

### ISSUE THREAD

**Issue by general2811** [BentoBoxWorld/Challenges#181]
This error pops up when i use /is challenges

```
[21:19:38 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'is challenges' in world.bentobox.bskyblock.commands.IslandCommand(island)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.14.4.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1135) ~[patched_1.14.4.jar:git-Paper-186]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-186]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
        at world.bentobox.challenges.ChallengesManager.lambda$new$0(ChallengesManager.java:129) ~[?:?]
        at java.util.TimSort.countRunAndMakeAscending(Unknown Source) ~[?:1.8.0_221]
        at java.util.TimSort.sort(Unknown Source) ~[?:1.8.0_221]
        at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_221]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_221]
        at world.bentobox.challenges.ChallengesManager.lambda$getAllChallenges$16(ChallengesManager.java:1452) ~[?:?]
        at java.util.Optional.map(Unknown Source) ~[?:1.8.0_221]
        at world.bentobox.challenges.ChallengesManager.getAllChallenges(ChallengesManager.java:1448) ~[?:?]
        at world.bentobox.challenges.ChallengesManager.getFreeChallenges(ChallengesManager.java:1465) ~[?:?]
        at world.bentobox.challenges.panel.user.ChallengesGUI.addFreeChallenges(ChallengesGUI.java:147) ~[?:?]
        at world.bentobox.challenges.panel.user.ChallengesGUI.build(ChallengesGUI.java:93) ~[?:?]
        at world.bentobox.challenges.commands.ChallengesCommand.execute(ChallengesCommand.java:80) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:233) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-186]
        ... 16 more

**Comment by BONNe** [comment]
If you would follow template I wouldn't need to spend time on stupid questions I need to ask you now.

Please, provide output of command `/bentobox version`

**Comment by general2811** [comment]
[22:13:00 INFO]: in Betrieb PAPER 1.14.4.
[22:13:00 INFO]: BentoBox version: 1.7.0-SNAPSHOT-b1361
[22:13:00 INFO]: commands.bentobox.version.database
[22:13:00 INFO]: Geladene Spielwelten:
[22:13:00 INFO]: acidisland_world (AcidIsland): Overworld, Nether, End
[22:13:00 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, End
[22:13:00 INFO]: caveblock-world (CaveBlock): Overworld, Nether, End
[22:13:00 INFO]: skygrid-world (SkyGrid): Overworld, Nether, End
[22:13:00 INFO]: Geladene Addons:
[22:13:00 INFO]: AcidIsland 1.7.0-SNAPSHOT-b437 (ENABLED)
[22:13:00 INFO]: BentoBox-InvSwitcher 1.6.0 (ENABLED)
[22:13:00 INFO]: Biomes 1.6.0.2-SNAPSHOT-b139 (ENABLED)
[22:13:00 INFO]: BSkyBlock 1.7.0-SNAPSHOT-b445 (ENABLED)
[22:13:00 INFO]: CaveBlock 1.6.1-SNAPSHOT-b152 (ENABLED)
[22:13:00 INFO]: Challenges 0.8.0-SNAPSHOT-#366 (ENABLED)
[22:13:00 INFO]: DimensionalTrees 1.6.0-SNAPSHOT (ENABLED)
[22:13:00 INFO]: Greenhouses 0.4.0-SNAPSHOT (ENABLED)
[22:13:00 INFO]: IslandFly 0.2.0 (ENABLED)
[22:13:00 INFO]: Level 1.7.0-SNAPSHOT-b282 (ENABLED)
[22:13:00 INFO]: Limits 1.6.1-SNAPSHOT-b164 (ENABLED)
[22:13:00 INFO]: MagicCobblestoneGenerator 1.5.0.1 (ENABLED)
[22:13:00 INFO]: SkyGrid 1.7.0-SNAPSHOT (ENABLED)
[22:13:00 INFO]: WelcomeWarps 1.6.2-SNAPSHOT-b179 (ENABLED)

**Comment by BONNe** [comment]
For me, it looks like one of your challenges has a level, that does not exist.

It is kinda weird, that it even manages to load, but yea, the issue is that level defined in one of your challenges does not exist in the database.

**Comment by BONNe** [comment]
So build #367 will not crash and will report which challenge is not valid in the log file.

**Comment by general2811** [comment]
no, has only appeared after the last update.

**Comment by general2811** [comment]
ok, I tested the last update. there is still an error displayed but the plugin can be opened ingame.
Now use build # 367.
[05:50:16 ERROR]: [BentoBox] Problem executing command executed by player - skipping!
the update has helped in any case before.

**Comment by BONNe** [comment]
Which was previous build you use, before the upgrade?
Is a new error message the same as it was previously?
Did in log file, when you first time run #367 build you saw a warning message like:
`[BentoBox] [Challenges] Challenge's SOME_CHALLENGE level was not found in the database. To avoid any errors with missing level, challenge was added to the FREE level!`

**Comment by general2811** [comment]
Challenges-0.8.0-SNAPSHOT-#366 was before.
I did not have any mistakes before
[latest.log](https://github.com/BentoBoxWorld/Challenges/files/3585045/latest.log)

**Comment by BONNe** [comment]
It only is telling that AcidIsland_novice and AcidIsland_expert levels are not in a database.

**Comment by general2811** [comment]
same error again with the new Challenges-0.9.0-SNAPSHOT-#381 build!

`ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'is challenges' in world.bentobox.bskyblock.commands.IslandCommand(island)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.14.4.jar:git-Paper-194]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-194]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-194]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-194]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-194]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-194]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-194]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-194]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-194]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-194]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-194]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013) ~[patched_1.14.4.jar:git-Paper-194]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-194]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-194]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-194]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:923) ~[patched_1.14.4.jar:git-Paper-194]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
	at world.bentobox.challenges.panel.CommonGUI.lambda$generateChallengeDescription$4(CommonGUI.java:426) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_221]
	at world.bentobox.challenges.panel.CommonGUI.generateChallengeDescription(CommonGUI.java:351) ~[?:?]
	at world.bentobox.challenges.panel.user.ChallengesGUI.getChallengeButton(ChallengesGUI.java:369) ~[?:?]
	at world.bentobox.challenges.panel.user.ChallengesGUI.addChallenges(ChallengesGUI.java:285) ~[?:?]
	at world.bentobox.challenges.panel.user.ChallengesGUI.build(ChallengesGUI.java:107) ~[?:?]
	at world.bentobox.challenges.commands.ChallengesCommand.execute(ChallengesCommand.java:80) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:233) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-194]
	... 16 more`

[21:16:59 INFO]: in Betrieb PAPER 1.14.4.
[21:16:59 INFO]: BentoBox version: 1.8.0-SNAPSHOT-b1403
[21:16:59 INFO]: Database: MYSQL
[21:16:59 INFO]: Geladene Spielwelten:
[21:16:59 INFO]: acidisland_world (AcidIsland): Overworld, Nether, End
[21:16:59 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, End
[21:16:59 INFO]: caveblock-world (CaveBlock): Overworld, Nether, End
[21:16:59 INFO]: skygrid-world (SkyGrid): Overworld, Nether, End
[21:16:59 INFO]: Geladene Addons:
[21:16:59 INFO]: AcidIsland 1.8.0-SNAPSHOT-b469 (ENABLED)
[21:16:59 INFO]: BentoBox-InvSwitcher 1.6.0 (ENABLED)
[21:16:59 INFO]: Biomes 1.6.0.2-SNAPSHOT-b141 (ENABLED)
[21:16:59 INFO]: BSkyBlock 1.8.0-SNAPSHOT-b481 (ENABLED)
[21:16:59 INFO]: CaveBlock 1.8.0-SNAPSHOT-b188 (ENABLED)
[21:16:59 INFO]: Challenges 0.9.0-SNAPSHOT-#381 (ENABLED)
[21:16:59 INFO]: ControlPanel 1.7.0-SNAPSHOT-#4 (ENABLED)
[21:16:59 INFO]: DimensionalTrees 1.6.0-SNAPSHOT (ENABLED)
[21:16:59 INFO]: Greenhouses 0.4.0-SNAPSHOT (ENABLED)
[21:16:59 INFO]: IslandFly 0.2.0 (ENABLED)
[21:16:59 INFO]: Level 1.7.0-SNAPSHOT-b282 (ENABLED)
[21:16:59 INFO]: Limits 1.6.1-SNAPSHOT-b164 (ENABLED)
[21:16:59 INFO]: MagicCobblestoneGenerator 1.5.0.1 (ENABLED)
[21:16:59 INFO]: SkyGrid 1.8.0-SNAPSHOT (ENABLED)
[21:16:59 INFO]: WelcomeWarps 1.6.2-SNAPSHOT-b179 (ENABLED)

**Comment by BONNe** [comment]
Your challenges are not migrated to the latest database version.
Please read release notes for 0.8.0 release.
