### ISSUE TITLE
Challenges 0.8.0 does not work with BentoBox 1.10.0 and Spigot 1.15.1

### ISSUE THREAD

**Issue by matbcvo** [BentoBoxWorld/Challenges#208]
#### Describe the bug

Challenges 0.8.0 does not work with BentoBox 1.10.0 and Spigot 1.15.1
It says that Challenges addon is enabled, but commands or anything else about challenges does not work.

#### Steps to reproduce the behavior

Spigot 1.15.1 + BentoBox 1.10.0 with BSkyBlock 1.10.0 and Challenges 0.8.0

##### BentoBox Version (Mandatory)

```
04.01 19:00:04 [Server] Server thread/INFO Running SPIGOT 1.15.1.
04.01 19:00:04 [Server] Server thread/INFO BentoBox version: 1.10.0
04.01 19:00:04 [Server] Server thread/INFO Database: JSON
04.01 19:00:04 [Server] Server thread/INFO Loaded Game Worlds:
04.01 19:00:04 [Server] Server thread/INFO bskyblock_world (BSkyBlock): Overworld, Nether, End
04.01 19:00:04 [Server] Server thread/INFO Loaded Addons:
04.01 19:00:04 [Server] Server thread/INFO Biomes 1.6.0.1
04.01 19:00:04 [Server] Server thread/INFO BSkyBlock 1.10.0
04.01 19:00:04 [Server] Server thread/INFO Challenges 0.8.0
04.01 19:00:04 [Server] Server thread/INFO ControlPanel 1.7.0
04.01 19:00:04 [Server] Server thread/INFO DimensionalTrees 1.6.0
04.01 19:00:04 [Server] Server thread/INFO Level 1.9.0
04.01 19:00:04 [Server] Server thread/INFO Limits 1.9.0
04.01 19:00:04 [Server] Server thread/INFO Warps 1.9.0
```

### Additional context (Optional)

Server console output: https://pastebin.com/raw/p2daD9mj

**Comment by BONNe** [comment]
Sorry, I cannot reproduce... 
For me, everything is working.

What exactly do commands say, when you write them?

**Comment by matbcvo** [comment]
It says _Unknown command. Type "/help" for help._

**Comment by BONNe** [comment]
It is because there does not exist command `/challenges` by default.
BentoBox supports multiple gamemodes and for each, it could have different challenges. The single command does not make any sense.

By default for skyblock to access to challenges: `/island challenges`

However, you can enable the single (`/challenge`) command via the config file, but server must be stopped before do that.

**Comment by matbcvo** [comment]
Sorry, now when I wrote /island challenges, then it shows challenges GUI, but when I click on e.g. Dye Maker challenge, then nothing happens and I'm getting error in server console:
```
[19:13:36] [Server thread/ERROR]: Could not pass event InventoryClickEvent to BentoBox v1.10.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2147) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at world.bentobox.challenges.database.object.Challenge.clone(Challenge.java:1129) ~[?:?]
	at world.bentobox.challenges.tasks.TryToComplete.<init>(TryToComplete.java:171) ~[?:?]
	at world.bentobox.challenges.tasks.TryToComplete.complete(TryToComplete.java:216) ~[?:?]
	at world.bentobox.challenges.tasks.TryToComplete.complete(TryToComplete.java:193) ~[?:?]
	at world.bentobox.challenges.panel.user.ChallengesGUI.lambda$getChallengeButton$11(ChallengesGUI.java:396) ~[?:?]
	at world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:55) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:53) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	... 17 more
[19:13:37] [Server thread/ERROR]: Could not pass event InventoryClickEvent to BentoBox v1.10.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2147) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at world.bentobox.challenges.database.object.Challenge.clone(Challenge.java:1129) ~[?:?]
	at world.bentobox.challenges.tasks.TryToComplete.<init>(TryToComplete.java:171) ~[?:?]
	at world.bentobox.challenges.tasks.TryToComplete.complete(TryToComplete.java:216) ~[?:?]
	at world.bentobox.challenges.tasks.TryToComplete.complete(TryToComplete.java:193) ~[?:?]
	at world.bentobox.challenges.panel.user.ChallengesGUI.lambda$getChallengeButton$11(ChallengesGUI.java:396) ~[?:?]
	at world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:55) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:53) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.1-b2542.jar:git-Spigot-05bb8bc-4b34472]
	... 17 more
```

**Comment by BONNe** [comment]
The challenges you are using are not up-to-date.
Is it from older challenges plugin?

**Comment by matbcvo** [comment]
What do you mean? I'm using Challenges 0.8.0 and it's latest as seen here: https://github.com/BentoBoxWorld/Challenges/releases

**Comment by BONNe** [comment]
"Tasks" that are used in an addon, are with wrong data format. 
From where did you get your data? 
Did you use challenges addon 0.7 or lover?

**Comment by matbcvo** [comment]
I now noticed that upgrade warning message in https://github.com/BentoBoxWorld/Challenges/releases/tag/0.8.0-Prerelease-1
I did /bsbadmin challenges migrate and now everything seems to work. Why migration has to be done manually, not automatically?
Thanks for quick reply.

**Comment by BONNe** [comment]
Cuz I was too lazy to do it.
