### ISSUE TITLE
Issues with challenges addon :o

### ISSUE THREAD

**Issue by DevilishDante** [BentoBoxWorld/Challenges#214]
#### Describe the bug

When i'm trying add à block needed around of player in challenge i have this error, and block isn't added : 
```JAVA
[07:43:42] [Server thread/ERROR]: Could not pass event InventoryClickEvent to BentoBox v1.11.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-56f8471-56118c6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-56f8471-56118c6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-56f8471-56118c6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2133) ~[spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot.jar:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot.jar:git-Spigot-56f8471-56118c6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoSuchFieldError: SIGN
        at world.bentobox.challenges.panel.util.SelectBlocksGUI.build(SelectBlocksGUI.java:146) ~[?:?]
        at world.bentobox.challenges.panel.util.SelectBlocksGUI.<init>(SelectBlocksGUI.java:64) ~[?:?]
        at world.bentobox.challenges.panel.admin.ManageBlocksGUI.lambda$createButton$2(ManageBlocksGUI.java:124) ~[?:?]
        at world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:55) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_151]
        at world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:53) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-56f8471-56118c6]
        ... 17 more
```

#### Steps to reproduce the behavior

try adding needed block around player in challenge menu then click on "add" :o 

#### Expected behavior

i think my block should be added ans he's not :o 

#### Screenshots and videos (Optional)

https://puu.sh/F4wz7/037dae29d6.PNG <-- screenshot

##### BentoBox Version (Mandatory)
```JAVA
[07:48:38] [Server thread/INFO]: Running SPIGOT 1.14.4.
[07:48:38] [Server thread/INFO]: BentoBox version: 1.11.0
[07:48:38] [Server thread/INFO]: Database: JSON
[07:48:38] [Server thread/INFO]: Loaded Game Worlds:
[07:48:38] [Server thread/INFO]: skyblock_iles (SkyBlock): Overworld, [nether_color]Nether, [end_color]End
[07:48:38] [Server thread/INFO]: Loaded Addons:
[07:48:38] [Server thread/INFO]: a2b 1.6.0 (ENABLED)
[07:48:38] [Server thread/INFO]: Biomes 1.6.0.1 (ENABLED)
[07:48:38] [Server thread/INFO]: BSkyBlock 1.11.0 (ENABLED)
[07:48:38] [Server thread/INFO]: Challenges 0.8.0-1.6.0 (ENABLED)
[07:48:38] [Server thread/INFO]: IslandFly 1.7.0 (ENABLED)
[07:48:38] [Server thread/INFO]: Level 1.8.0 (ENABLED)
[07:48:38] [Server thread/INFO]: Likes 1.7.0 (ENABLED)
[07:48:38] [Server thread/INFO]: Limits 1.7.0 (ENABLED)
[07:48:38] [Server thread/INFO]: MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
[07:48:38] [Server thread/INFO]: VoidPortals 1.5.0.0 (ENABLED)
[07:48:38] [Server thread/INFO]: Warps 1.8.1 (ENABLED)

```

#### Plugins (Optional)

```JAVA
[07:49:19] [Server thread/INFO]: Plugins (46): LuckPerms, WorldEdit, LogBlock, PlaceholderAPI, ConsoleSpamFix, WorldGuard, ProtocolLib, LibsDisguises, MVdWPlaceholderAPI, IPWhitelist, VoxelSniper, UltraBar, WildSkript, EditableSign, FeatherBoard, Vault, Skript, Essentials, AnimatedNames, skDragon, skript-db, SkQuery, ExtrasSK, HeadDatabase, HolographicDisplays, Ersatz, TeamSkript, WolvSK, SkMorkaz, SK-NBeeT, HolographicDisplaysExtension, Citizens, skRayFall, BentoBox, EssentialsChat, TradePlus, skUtilities, TwitterSK, skript-mirror, Multiverse-Core, Skellett, Shopkeepers, SharpSK, SkUniversal, TuSKe, CrateReloaded

```
 
### Additional context (Optional)
Thanks you for your time and read me :)
Edit : i doesn't have post in right section :/ sorry about that, and i don't find how to delete :o

**Comment by DevilishDante** [comment]
> 
> 
> Your server version is 1.14.4
> BentoBox version is 1.11.0
> there is no reason why you should use Challenges 0.8.0-1.6.0!
> 
> 0.8.0-1.6.0 is made for 1.13.2 version of Minecraft.

mhhh okay but how can i have challenges if i can't use challenge addon? :o 
it is included in BentoBox or Bskyblock already? :o

**Comment by BONNe** [comment]
OMG.
YOU NEED 0.8.0 VERSION without 1.6.0 at the end~!!!!!!

**Comment by DevilishDante** [comment]
> 
> 
> OMG.
> YOU NEED 0.8.0 VERSION without 1.6.0 at the end~!!!!!!

mh thanks you i guest :x
