### ISSUE TITLE
Challenge Addon Update Error

### ISSUE THREAD

**Issue by Manu5656** [BentoBoxWorld/Challenges#260]
Hi, I have updated bentobox and all the addons including the challenge one.

Before I used "Challenges-0.8.0-SNAPSHOT-.323" and the challenges work correctly but obviously it is not fully compatible with the latest version of Bentobox so I am forced to update the challenge addon to the latest version as well.

With the latest version, the "challenges-0.8.3" the challenges don't work, if I try to click on one of them I get these errors in the console

I hope you can help me solve the problem and I sincerely hope not to lose the hundreds of challenges I had already created.

This is what happens when I try to click on a challenge:
(Server Version: PaperSpigot 1.16.2)

`[17:12:38 ERROR]: Could not pass event InventoryClickEvent to BentoBox v1.14.2
java.lang.NullPointerException: null
        at world.bentobox.challenges.database.object.Challenge.clone(Challenge.java:1134) ~[?:?]
        at world.bentobox.challenges.tasks.TryToComplete.<init>(TryToComplete.java:181) ~[?:?]
        at world.bentobox.challenges.tasks.TryToComplete.complete(TryToComplete.java:226) ~[?:?]
        at world.bentobox.challenges.tasks.TryToComplete.complete(TryToComplete.java:203) ~[?:?]
        at world.bentobox.challenges.panel.user.ChallengesGUI.lambda$getChallengeButton$11(ChallengesGUI.java:397) ~[?:?]
        at world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:56) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_252]
        at world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:54) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor873.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-180]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-180]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-180]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-180]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2422) ~[patched_1.16.2.jar:git-Paper-180]
        at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.2.jar:git-Paper-180]
        at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.2.jar:git-Paper-180]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-180]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-180]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-180]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-180]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-180]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-180]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-180]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-180]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-180]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-180]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-180]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

**Comment by Manu5656** [comment]
Let me know as soon as possible because this error is wasting me a lot of time and delaying the opening of the server .. thanks in advance and good job.

**Comment by fredthedoggy** [comment]
@Manu5656 First, Could you list your other plugins on the server, and second, could you try this on paper's latest release? (184)

**Comment by BONNe** [comment]
This is not related with a paper version.

There are 2 possibilities: 
1) It can be fixed with just /[command] challenges migrate
2) One challenge contains broken items (null) due Spigot server update.

**Comment by Manu5656** [comment]
@BONNe 

`> acid challenges migrate
[20:12:23 INFO]: [BentoBox] [Challenges] Starting migration to new data format.
[20:12:23 INFO]: [BentoBox] [Challenges] All data is valid. Migration is not necessary.`

I have already tried with the migration and I see this .. the only thing that comes to mind now is to try to remove each challenge individually and see if it works. If the problem is a corrupt challenge in this way I should be able to identify it, beyond this I don't know.

**Comment by Manu5656** [comment]
I removed and reloaded them one by one (without making any changes) and now it seems to work, strange but it is so ..

But once I have completed all the challenges of the first level, it does not make me open the second level. Why? I don't have any console errors, could it be a configuration problem? Even though I haven't changed anything since they worked
