### ISSUE TITLE
Next page in the mission page is not clickabe

### ISSUE THREAD

**Issue by jack444410** [BentoBoxWorld/Challenges#318]
### Expected behavior

When I click on the next page, it should show the left missions in the next page.

### Observed/Actual behavior

It will become clickable when I click it second time.
But it shows an empty page to me. (there are missions left.)

### Steps/models to reproduce

[22:06:57] [Server thread/ERROR]: Could not pass event InventoryClickEvent to BentoBox v1.23.2-SNAPSHOT-b2385
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
	at java.lang.String.replace(String.java:2957) ~[?:?]
	at world.bentobox.bentobox.api.user.User.replaceVars(User.java:491) ~[BentoBox-1.23.2-SNAPSHOT-b2385.jar:?]
	at world.bentobox.bentobox.api.user.User.translate(User.java:448) ~[BentoBox-1.23.2-SNAPSHOT-b2385.jar:?]
	at world.bentobox.bentobox.api.user.User.getTranslation(User.java:421) ~[BentoBox-1.23.2-SNAPSHOT-b2385.jar:?]
	at world.bentobox.bentobox.api.user.User.getTranslationOrNothing(User.java:512) ~[BentoBox-1.23.2-SNAPSHOT-b2385.jar:?]
	at world.bentobox.challenges.utils.Utils.prettifyObject(Utils.java:870) ~[Challenges-1.2.0-SNAPSHOT-b513.jar:?]
	at world.bentobox.challenges.utils.Utils.prettifyObject(Utils.java:581) ~[Challenges-1.2.0-SNAPSHOT-b513.jar:?]
	at world.bentobox.challenges.panel.CommonPanel.lambda$generateInventoryChallenge$7(CommonPanel.java:448) ~[Challenges-1.2.0-SNAPSHOT-b513.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at world.bentobox.challenges.panel.CommonPanel.generateInventoryChallenge(CommonPanel.java:440) ~[Challenges-1.2.0-SNAPSHOT-b513.jar:?]
	at world.bentobox.challenges.panel.CommonPanel.generateRequirements(CommonPanel.java:320) ~[Challenges-1.2.0-SNAPSHOT-b513.jar:?]
	at world.bentobox.challenges.panel.CommonPanel.generateChallengeDescription(CommonPanel.java:160) ~[Challenges-1.2.0-SNAPSHOT-b513.jar:?]
	at world.bentobox.challenges.panel.user.ChallengesPanel.createChallengeButton(ChallengesPanel.java:275) ~[Challenges-1.2.0-SNAPSHOT-b513.jar:?]
	at world.bentobox.challenges.panel.user.ChallengesPanel.createChallengeButton(ChallengesPanel.java:245) ~[Challenges-1.2.0-SNAPSHOT-b513.jar:?]
	at world.bentobox.bentobox.api.panels.TemplatedPanel.makeAddonButton(TemplatedPanel.java:429) ~[BentoBox-1.23.2-SNAPSHOT-b2385.jar:?]
	at world.bentobox.bentobox.api.panels.TemplatedPanel.makeButton(TemplatedPanel.java:373) ~[BentoBox-1.23.2-SNAPSHOT-b2385.jar:?]
	at world.bentobox.bentobox.api.panels.TemplatedPanel.populateInventoryPanel(TemplatedPanel.java:116) ~[BentoBox-1.23.2-SNAPSHOT-b2385.jar:?]
	at world.bentobox.bentobox.api.panels.TemplatedPanel.generatePanel(TemplatedPanel.java:69) ~[BentoBox-1.23.2-SNAPSHOT-b2385.jar:?]
	at world.bentobox.bentobox.api.panels.TemplatedPanel.<init>(TemplatedPanel.java:57) ~[BentoBox-1.23.2-SNAPSHOT-b2385.jar:?]
	at world.bentobox.bentobox.api.panels.builders.TemplatedPanelBuilder.build(TemplatedPanelBuilder.java:150) ~[BentoBox-1.23.2-SNAPSHOT-b2385.jar:?]
	at world.bentobox.challenges.panel.user.ChallengesPanel.build(ChallengesPanel.java:107) ~[Challenges-1.2.0-SNAPSHOT-b513.jar:?]
	at world.bentobox.challenges.panel.user.ChallengesPanel.lambda$createNextButton$28(ChallengesPanel.java:694) ~[Challenges-1.2.0-SNAPSHOT-b513.jar:?]
	at world.bentobox.bentobox.listeners.PanelListenerManager.lambda$onInventoryClick$0(PanelListenerManager.java:56) ~[BentoBox-1.23.2-SNAPSHOT-b2385.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at world.bentobox.bentobox.listeners.PanelListenerManager.onInventoryClick(PanelListenerManager.java:54) ~[BentoBox-1.23.2-SNAPSHOT-b2385.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1948.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-511]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-511]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-511]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3189) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-511]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-511]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-511]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-511]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-511]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-511]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-511]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-511]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### BentoBox version

 https://paste.md-5.net/zenoxuliqu

[latest.log](https://github.com/BentoBoxWorld/Challenges/files/11303944/latest.log)

### Plugin list

 Plugins (110): AdvancedChests, AdvancedRegionMarket, ArmShopBridge, ArtMap, BSkyBlock, BentoBox, BetterShulkerBoxes, BetterTridents, Biomes, BlueShop, BossShopPro, BungeeTabListPlus, CMI, CMILib, CactusFarmOptimizer, CalendarEvents, Challenges, ChestShop, ChestSort, Citizens, CommandPanels, CommandSigns, CompatNoCheatPlus, ConditionalCommands, ConsoleSpamFix, CraftBook, CrateReloaded, CustomCrafting, CustomPiglinsTrades, DiscordReward, DiscordSRV, Elevator, ExtraContexts, GCore, GSit, HeadDatabase, HexChatColour, HoloMedalsNew, HolographicDisplays, Hyperverse, InteractiveChat, InteractiveChatDiscordSrvAddon, ItemBlocker, ItemEdit, ItemTag, ItemsAdder, JetsMinions, LWC, LWCTrust, Level, LibsDisguises, LightAPI, LimitedUses, Limits, LiteBans, LiteSignIn, LoneLibs, LuckPerms, LuckPermsTmpNoticer, MCPerks, MarketPlace, MenuGroup, MineSecure, MobFarmManager, MythicMobs, NBTAPI, NCPDragDown, NoCheatPlus, NoSpawnerChange, OreRegenerator, OtherDrops, PhatLoots, Pl-Hide-Pro, PlaceholderAPI, Plan, PlayerPoints, PlayerWarps, PlugManX, ProtocolLib, PsudoCommand, QuestCreator, QuickShop, RandomCommand, RemoteCommands, RoseLoot, RoseStacker, SCore, SafariNet, SelectionVisualizer, ServerUtils, ShiftAndF, Shopkeepers, Skypatch117, TradeSystem, UpgradeableHoppers, Vault, ViaBackwards, ViaVersion, VillagerTradeLimiter, VoidGen, WGEF-Reborn, WolfyUtilities, WorldBorder, WorldEdit, WorldGuard, XConomy, boosCooldowns, gProtector, mcMMO and spark

### Other

![image](https://user-images.githubusercontent.com/72694726/233845321-bcacaf2d-d1d4-405e-ac46-5eec984aa568.png)
![image](https://user-images.githubusercontent.com/72694726/233845325-cc39854e-2a7d-4347-a184-8e1249cd866b.png)

**Comment by BONNe** [comment]
By stack trace it looks like the issue was with written or writable books. Should be fixed in the latest dev version.
