### ISSUE TITLE
Potions for Required Items causes Challenges to Error

### ISSUE THREAD

**Issue by TreemanKing** [BentoBoxWorld/Challenges#350]
### Expected behavior

Be able to do `/challenges` without error.

### Observed/Actual behavior

"Internal error occurred."
```
[17:38:00] [Server thread/INFO]: playerissued server command: /island challenges
[17:38:00] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'island challenges' in world.bentobox.bskyblock.BSkyBlock$1(island)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[PaperCrane-API-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987) ~[papercrane-1.20.1.jar:git-Paper-"27e1e23"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2558) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.chat(CraftPlayer.java:705) ~[papercrane-1.20.1.jar:git-Paper-"27e1e23"]
	at it.emmerrei.mycommand.execute.DispatchCommands.ExecuteCommands(DispatchCommands.java:1454) ~[MyCommand.jar:?]
	at it.emmerrei.mycommand.execute.DispatchCommands.PerformMycmdCommands(DispatchCommands.java:1313) ~[MyCommand.jar:?]
	at it.emmerrei.mycommand.execute.DispatchCommands.ExecuteMyCommandCommands(DispatchCommands.java:525) ~[MyCommand.jar:?]
	at it.emmerrei.mycommand.commands.CmdCustomCommands.onCommand(CmdCustomCommands.java:145) ~[MyCommand.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[PaperCrane-API-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[PaperCrane-API-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987) ~[papercrane-1.20.1.jar:git-Paper-"27e1e23"]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[papercrane-1.20.1.jar:git-Paper-"27e1e23"]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[papercrane-1.20.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2359) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2319) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[papercrane-1.20.1.jar:git-Paper-"27e1e23"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1337) ~[papercrane-1.20.1.jar:git-Paper-"27e1e23"]
	at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:197) ~[papercrane-1.20.1.jar:git-Paper-"27e1e23"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1314) ~[papercrane-1.20.1.jar:git-Paper-"27e1e23"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1307) ~[papercrane-1.20.1.jar:git-Paper-"27e1e23"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1285) ~[papercrane-1.20.1.jar:git-Paper-"27e1e23"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[papercrane-1.20.1.jar:git-Paper-"27e1e23"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[papercrane-1.20.1.jar:git-Paper-"27e1e23"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Steps/models to reproduce

1. Make or edit existing challenge
2. Go to required items
3. Add potions to required items (standard potions like resistance 1 potion etc)
4. Save
5. Do `/challenges`
6. Error

### BentoBox version

BB Version 2.4.1
Challenges 1.3.0

### Plugin list

N/A

### Other

For future reference, it should have a fail case where it replaced it with a replacement item. It shouldn't error and cause the whole command to not work.

**Comment by BONNe** [comment]
The issue is that Spigot changed potions in 1.20.4 (if I remember correctly)
So potions are not compatible with Minecraft 1.20.1
