### ISSUE TITLE
When I'm editing the name of the challenge and it is automatically cancelled due to a long time, the following error will occur and then I can't edit any challenges.

### ISSUE THREAD

**Issue by Noogear** [BentoBoxWorld/Challenges#362]
### Expected behavior

Be able to edit the challenge normally

### Observed/Actual behavior

As long as I click on any challenge, this error will be reported.

### Steps/models to reproduce

When I'm editing the name of the challenge and it is automatically cancelled due to a long time, the following error will occur and then I can't edit any challenges. The specific situation is that as long as I click on any challenge, this error will be reported.
[message.txt](https://github.com/user-attachments/files/17491480/message.txt)

### BentoBox version

```
[12:46:14 INFO]: 运行在: PAPER 1.21.1.
[12:46:14 INFO]: (1.21.1-DEV-09fa2d6 (MC: 1.21.1))
[12:46:14 INFO]: BentoBox版本: 2.6.0
[12:46:14 INFO]: 数据库类型: JSON
[12:46:14 INFO]: 已加载的世界:
[12:46:14 INFO]: oneblock_world (OneBlock): 主世界, 下界
[12:46:14 INFO]: 已加载的附加组件(Addons):
[12:46:14 INFO]: AOneBlock 1.17.1-SNAPSHOT-b413 (ENABLED)
[12:46:14 INFO]: Biomes 2.2.0-SNAPSHOT-b277 (ENABLED)
[12:46:14 INFO]: Challenges 1.3.2-SNAPSHOT-b565 (ENABLED)
[12:46:14 INFO]: Level 2.15.0-SNAPSHOT-b586 (ENABLED)
[12:46:14 INFO]: TopBlock 1.0.2-SNAPSHOT-b27 (ENABLED)
[12:46:14 INFO]: Warps 1.15.1-SNAPSHOT-b373 (ENABLED)
```

### Plugin list

```
[12:46:37 INFO]:  - Aiyatsbus, AuraMobs, AuraSkills, AuthMe, BentoBox, BentoBox-AOneBlock, BentoBox-Biomes, BentoBox-Challenges, BentoBox-Level, BentoBox-TopBlock
[12:46:37 INFO]:  BentoBox-Warps, Chesed, CoinsEngine, ColorfulMap, CombatPets, Craftorithm, DamageDisplay, DecentHolograms, easyTools, ExcellentShop
[12:46:37 INFO]:  LuckPerms, MythicPrefixes, nightcore, Oraxen, PetNameFix, PlaceholderAPI, protectall, ProtocolLib, QFSoulBag, QuickSave
[12:46:37 INFO]:  SunLight, TileDataSaver, TrMenu, UTitleAuth, Vault, WanderingTrades, WildChests, WorldEditz
```

**Comment by Noogear** [comment]
```
[01:54:13 WARN]: java.lang.IllegalArgumentException: Comparison method violates its general contract!
[01:54:13 WARN]:        at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
[01:54:13 WARN]:        at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
[01:54:13 WARN]:        at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
[01:54:13 WARN]:        at java.base/java.util.TimSort.sort(TimSort.java:245)
[01:54:13 WARN]:        at java.base/java.util.Arrays.sort(Arrays.java:1307)
[01:54:13 WARN]:        at java.base/java.util.ArrayList.sort(ArrayList.java:1805)
[01:54:13 WARN]:        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392)
[01:54:13 WARN]:        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
[01:54:13 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:557)
[01:54:13 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
[01:54:13 WARN]:        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[01:54:13 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
[01:54:13 WARN]:        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:702)
[01:54:13 WARN]:        at Challenges-1.3.2-SNAPSHOT-b565-1729734502856.jar//world.bentobox.challenges.managers.ChallengesManager.lambda$getAllChallenges$22(ChallengesManager.java:1788)
[01:54:13 WARN]:        at java.base/java.util.Optional.map(Optional.java:260)
[01:54:13 WARN]:        at Challenges-1.3.2-SNAPSHOT-b565-1729734502856.jar//world.bentobox.challenges.managers.ChallengesManager.getAllChallenges(ChallengesManager.java:1784)
[01:54:13 WARN]:        at Challenges-1.3.2-SNAPSHOT-b565-1729734502856.jar//world.bentobox.challenges.managers.ChallengesManager.getTotalChallengeCompletionCount(ChallengesManager.java:1981)
[01:54:13 WARN]:        at Challenges-1.3.2-SNAPSHOT-b565-1729734502856.jar//world.bentobox.challenges.ChallengesAddon.lambda$registerPlaceholders$8(ChallengesAddon.java:345)
[01:54:13 WARN]:        at BentoBox-2.6.0.jar//world.bentobox.bentobox.api.placeholders.placeholderapi.BasicPlaceholderExpansion.onPlaceholderRequest(BasicPlaceholderExpansion.java:48)
[01:54:13 WARN]:        at BentoBox-2.6.0.jar//world.bentobox.bentobox.api.placeholders.placeholderapi.AddonPlaceholderExpansion.onPlaceholderRequest(AddonPlaceholderExpansion.java:7)
[01:54:13 WARN]:        at PlaceholderAPI-2.11.7-DEV-200.jar//me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32)
[01:54:13 WARN]:        at PlaceholderAPI-2.11.7-DEV-200.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[01:54:13 WARN]:        at PlaceholderAPI-2.11.7-DEV-200.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[01:54:13 WARN]:        at PlaceholderAPI-2.11.7-DEV-200.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.taboolib.platform.compat.PlaceholderExpansionKt.replacePlaceholder(PlaceholderExpansion.kt:20)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.module.display.MenuSession.parse(MenuSession.kt:147)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.module.display.item.Lore.parse(Lore.kt:32)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.module.display.item.Item.parsedLore(Item.kt:63)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.module.display.item.Item.build$default(Item.kt:104)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.module.display.item.Item.get(Item.kt:67)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:77)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.module.display.icon.Icon.filter(Icon.kt:153)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.module.display.icon.Icon.onRefresh(Icon.kt:82)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.module.display.Menu.loadIcon(Menu.kt:185)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.module.display.Menu.open(Menu.kt:105)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.module.display.Menu.open$default(Menu.kt:61)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.module.internal.listener.ListenerCommand.onCommand(ListenerCommand.kt:25)
[01:54:13 WARN]:        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:112)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:110)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:80)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:80)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:36)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:36)
[01:54:13 WARN]:        at TrMenu-3.3.4.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:57)
[01:54:13 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:54:13 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:65)
[01:54:13 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[01:54:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[01:54:13 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2323)
[01:54:13 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2284)
[01:54:13 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:54:13 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[01:54:13 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[01:54:13 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573)
[01:54:13 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:190)
[01:54:13 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[01:54:13 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551)
[01:54:13 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544)
[01:54:13 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[01:54:13 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1492)
[01:54:13 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1502)
[01:54:13 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1346)
[01:54:13 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[01:54:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[01:54:13 INFO]: ICON: 1
```
t seems that players can't use challenges normally either.

**Comment by tastybento** [comment]
I think there are two issues here mixed together.

1. When a conversation is ongoing, you cannot enter another conversation. So that can be why clicking on an icon to change the name or whatever is blocked. I think the Bukkit Conversation API is a bit buggy, but I have added some code that may help. I am not sure.

2. The error you received seems to be caused by a null challenge Level. I added better comparison/sorting code to handle this. 

So, please try the latest snapshot and let me know if that works for you.
